version: '3.8'

services:
  jbprojector:
    image: projector-pycharm-p:2021.3.1
    restart: always
    volumes:
      - ~/projector:/home/projector-user
    network_mode: "host"
#    ports:
#      - 8123:8123  # home assistant
#      - 8887:8887
  gitkraken:
    build:
      context: ./gitkraken
      dockerfile: ./gitkraken/Dockerfile
    cap_add:
      - SYS_ADMIN
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ~/projector/Gitkraken:/config
    environment:
      - PUID=1000
      - PGID=1000
